# Generated by Django 5.0.2 on 2024-03-26 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(blank=0, max_length=20, null=0)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='NotificacionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=0, max_length=255, null=0)),
                ('motivo', models.TextField(blank=0, null=0)),
                ('estado', models.CharField(blank=0, max_length=50, null=0)),
                ('fecha', models.DateField()),
                ('fecha_notificacion', models.DateField(default=django.utils.timezone.now)),
                ('visto', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=0, max_length=25, null=0)),
                ('anno', models.IntegerField()),
                ('bajas', models.IntegerField()),
                ('continuidad', models.IntegerField()),
                ('licencias', models.IntegerField()),
                ('traslados', models.IntegerField()),
                ('a_bajas', models.IntegerField()),
                ('a_continuidad', models.IntegerField()),
                ('a_licencias', models.IntegerField()),
                ('a_traslados', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
                ('grupo', models.CharField(blank=0, max_length=20, null=0)),
                ('anno', models.IntegerField(default=1)),
            ],
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='NotificacionSolicitudEstudiante',
            fields=[
                ('notificacionsolicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.notificacionsolicitud')),
            ],
            bases=('app.notificacionsolicitud',),
        ),
        migrations.CreateModel(
            name='NotificacionSolicitudSecretario',
            fields=[
                ('notificacionsolicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.notificacionsolicitud')),
            ],
            bases=('app.notificacionsolicitud',),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=0, choices=[('baja', 'Baja'), ('continuidad', 'Continuidad de Estudios'), ('licencia', 'Licencia'), ('traslado', 'Traslado')], max_length=255, null=0)),
                ('motivo', models.TextField(blank=0, null=0)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='notificacionsolicitud',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante'),
        ),
    ]
