# Generated by Django 5.0.2 on 2024-03-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='notificacionsolicitud',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notifiaciones'},
        ),
        migrations.AlterModelOptions(
            name='notificacionsolicitudestudiante',
            options={'verbose_name': 'NotificacionEstudiante', 'verbose_name_plural': 'NotifiacionesEstudiante'},
        ),
        migrations.AlterModelOptions(
            name='notificacionsolicitudsecretario',
            options={'verbose_name': 'NotificacionSecretario', 'verbose_name_plural': 'NotifiacionesSecretario'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiantes',
        ),
        migrations.AlterModelTable(
            name='notificacionsolicitud',
            table='notificaciones',
        ),
        migrations.AlterModelTable(
            name='notificacionsolicitudestudiante',
            table='notificaciones_estudiante',
        ),
        migrations.AlterModelTable(
            name='notificacionsolicitudsecretario',
            table='notificaciones_secretario',
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='reportes',
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='solicitudes',
        ),
    ]
