# Generated by Django 5.0.2 on 2024-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Denegado', 'Denegado')], default='Pendiente', max_length=50),
        ),
    ]
